name: PosSpacer
channels:
  - anaconda
  - conda-forge
  - bioconda
dependencies:
  - biopython
  - cutadapt
  - numpy
  - pandas
  - ipykernel
  - pear
  - multiqc
  - seqkit
  - polars
  - pyarrow
  - ca-certificates
  - certifi
  - openssl

